### ISSUE TITLE
%q should be an empty string if it's empty, not '-'

### ISSUE THREAD

**Issue by miyagawa** [lestrrat/go-apache-logformat#14]
> %q	The query string (prepended with a ? if a query string exists, otherwise an empty string).

**Comment by miyagawa** [comment]
There seems to be other fields that fall into this bug as well, because you supply `'-'` as a replacement for empty fields everywhere.

**Comment by lestrrat** [comment]
@miyagawa haven't tested *everything*, but hopefully #16 gets it: can you give it a try? I'm half way into doing #15, but would like to land this first.
