### ISSUE TITLE
%{usec}t is handled as elapsed

### ISSUE THREAD

**Issue by miyagawa** [lestrrat/go-apache-logformat#15]
It seems you get `T` and `t` mixed up in the block handler.

`%t` is request time, and takes `usec`, `msec` etc. to get microsecs from the Epoch.
`%T` is time taken for a request (elapsed) and takes `us`, `ms` to get them in micro/millisec.

you're handling `%{usec}t` as elapsed, which seems wrong to me - it should be displaying microseconds from the epoch.

**Comment by lestrrat** [comment]
@miyagawa Can you give a cursory look, please? :)

**Comment by lestrrat** [comment]
Ah.. wait, I guess msec_frac and usec_frac are also fractions based on request time since the epoch..

**Comment by lestrrat** [comment]
fixed. @miyagawa pls take a look when you have the time
